apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: kube-system
spec:
  hostname: ubuntu
  hostPID: true
  hostNetwork: true
  containers:
  - image: ubuntu
    command:
      - sleep
      - "14d"
    name: ubuntu
    securityContext:
      privileged: true
    volumeMounts:
    - name: dev
      mountPath: /dev
    - name: root
      mountPath: /mnt/root
      readOnly: true
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
    - name: tmp
      mountPath: /tmp
  priorityClassName: system-node-critical
  tolerations:
    - operator: Exists
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
  volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: root
      hostPath:
        path: /
    - hostPath:
        path: /lib/modules
      name: lib-modules
    - name: tmp
      emptyDir:
        medium: Memory
