apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: csi-pd-zonal-ssd-xfs
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-ssd
  csi.storage.k8s.io/fstype: xfs
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: csi-pd-regional-ssd-xfs
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-ssd
  csi.storage.k8s.io/fstype: xfs
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: csi-pd-zonal-hdd-xfs
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-standard
  csi.storage.k8s.io/fstype: xfs
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: csi-pd-zonal-balanced-xfs
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: xfs
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
