[Global]
auth-url=${auth}v3/
tenant-id=${project_id}
domain-id=${project_domain_id}
region=${region}
username=${username}
password=${password}
[Networking]
public-network-name=${network_public_name}
[Metadata]
search-order=metadataService
